# Copyright 2021 Canonical
# See LICENSE file for licensing details.

options:

  ### Application-related options:
  server-deployment-mode:
    type: string
    # TODO(aznashwan): check what other possible modes there are and
    # offer a more detailed description on them.
    default: TEST_IGNORE_FUNCTION_MATCH
    description: Server deployment mode.
  
  # TODO(aznashwan): add a separate option for https endpoints?
  # Will need to see what certificates needs installing and where.

  server-logging-level:
    type: string
    default: INFO
    description: |
      String identifier of the log level to be used for all library classes.
      Must be one of INFO, WARN, DEBUG, or TRACE, or OFF.

  server-pac4j-logging-level:
    type: string
    default: DEBUG
    description: |
      String identifier of the log level to be used by authentication-related
      PAC4J actions. Must be one of INFO, WARN, DEBUG, or TRACE, or OFF.

  # TODO(aznashwan): ask whether 'opentracing' options are worth exposing.
  # https://github.com/finos/legend/blob/master/installers/docker-compose/shared/templates/engine/config.json#L45
